name: The Automated Forge (CI DevSecOps)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build, Segurança e Qualidade
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório (Checkout)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Preparar o ambiente Java 21 (JDK)
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache NVD Vulnerability Database
        uses: actions/cache@v5
        with:
          path: ~/.nvd-data
          key: nvd-data-${{ runner.os }}-

      - name: Dar permissão de execução ao Gradle
        run: chmod +x gradlew

      - name: Executar Build, Testes e OWASP SCA
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: ./gradlew clean check dependencyCheckAnalyze

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: jacoco-reports
          path: '**/build/reports/jacoco/test/jacocoTestReport.xml'
          retention-days: 7

      - name: SonarCloud Security Scan
        if: sucess()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          ./gradlew sonar
          -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
          -Dsonar.organization=${{ github.repository_owner }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.coverage.jacoco.xmlReportPaths=book-examples/build/reports/jacoco/test/jacocoTestReport.xml,real-world-implementations/build/reports/jacoco/test/jacocoTestReport.xml